### ISSUE TITLE
Incorrect Username

### ISSUE THREAD

**Issue by dnadawa** [Achintha444/mailerTemp#1]
When i write this code it is showing Message not sent. Incorrect username / password / credentials

**Comment by Achintha444** [comment]
Can you show where the error is showing?

**Comment by Achintha444** [comment]
And please check whether your entered email and password are correct

**Comment by dnadawa** [comment]
They are correct.

**Comment by Achintha444** [comment]
https://support.google.com/accounts/answer/6010255?p=lsa_blocked&hl=en&visit_id=637166894705530050-3789727984&rd=1
Go to this page and 'ON' the status of Less secure of app of your google account, otherwise, the google would not let you send emails.
Hope this helps!
